---

- name: add yarn repo's key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present 

- name: put yarn repository
  apt_repository:
    repo: deb http://dl.yarnpkg.com/debian/ stable main
    state: present

- name: install nodejs and npm from repo
  apt: 
    name="{{ item }}"
    state=present
    update_cache='yes'
  with_items:
    - npm
    - nodejs-legacy
    - yarn

- name: install gulp
  command: npm install -g gulp tern tern-jsx
